### ISSUE TITLE
When I compile the provided w_corne code in vial-qmk, I get errors

### ISSUE THREAD

**Issue by Voidlighter** [KeyClicks/Split-Keyboard#1]
```
⚠ keyclicks/w_corne: RGBLED_NUM->rgblight.led_count: invalid literal for int() with base 10: 'DRIVER_LED_TOTAL'
☒ keyclicks/w_corne: RGB_DI_PIN in config.h is no longer a valid option and should be replaced with WS2812_DI_PIN or APA102_DI_PIN
☒ keyclicks/w_corne: RGBLIGHT_ANIMATIONS in config.h is no longer a valid option and should be removed

 * RGB_MATRIX_DRIVER=WS2812 is not a valid matrix type                                                 [ERRORS]

builddefs/common_features.mk:422: *** Invalid RGB_MATRIX_DRIVER.  Stop.
Make finished with errors
make: *** [Makefile:392: keyclicks/w_corne:vial:flash] Error 1
```

Look, I'm rather new to this, so I could be missing something—thought I don't know why compiling the base code should give errors. (I'm compiling with `qmk flash -kb keyclicks/w_corne -km vial`)

**Comment by KeyClicks** [comment]
Sorry for the delay, you could use "make keyclicks/w_corne:vial" to build vial firmware(.vfw). Then use vibl to flash your firmware.
![Snipaste_2024-02-07_01-32-35](https://github.com/KeyClicks/Split-Keyboard/assets/115432051/f315c66c-5a6b-4753-b874-a14c680976d5)

**Comment by KeyClicks** [comment]
Sorry for the delay, use "make keyclicks/w_corne:vial" to build your firmware(.vfw). Vibl to update firmware

![Snipaste_2024-02-07_01-32-35](https://github.com/KeyClicks/Split-Keyboard/assets/115432051/0e309981-984e-4b13-9f7a-e85001b5e6d7)

**Comment by KeyClicks** [comment]
Sorry for the delay, try "make keyclicks/w_corne:vial" to build your firmware(.vfw). Vibl to update firmware

![Snipaste_2024-02-07_01-32-35](https://github.com/KeyClicks/Split-Keyboard/assets/115432051/0d6ab70d-357a-471e-9d0f-257d241c760e)
